### ISSUE TITLE
hourly charts show incorrect data

### ISSUE THREAD

**Issue by szamanr** [metalfoxdev/Raindrop#13]
this is hourly stats (option "1") (shows correct data i think):
![hourly data](https://github.com/metalfoxdev/Raindrop/assets/2622838/5ae13fba-d7b6-4d64-bd82-8f4d5b3dee19)

this is hourly charts (option "3") - it has several issues:
a. shows incorrect temperature data
b. shows incorrect unit for temperature (kmh)
c. shows incorrect data for wind (not sure which one is correct, but you can see the discrepancy between screenshots)
d. does not round numbers correctly

![hourly charts](https://github.com/metalfoxdev/Raindrop/assets/2622838/5873cf14-7fc4-492b-b199-026fe650a633)

**Comment by metalfoxdev** [comment]
I have fixed problem A, B and C but the number rounding issue is a tricky one because the plotext module (the module I use for plotting the graphs) seems to process a float object using a float() operator which results in those weird zeroes. Those zeroes are not in the raw json weather data so I need to work out how to stop plotext from messing up the floats. I know you can use an f-string to remove trailing zeroes and it works but plotext just reverses it when it re-runs the float through a float() operator again (without any f-string formatting afterwards). I am currently working on a fix. :)

**Comment by metalfoxdev** [comment]
I have decided to convert the float temperatures to integers for the charts. The decimal values are still accessible from the hourly menu because the display system used there is a custom one made for the program so i can therefore format the strings accordingly
